create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  nome text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists clientes_nome_unico
  on public.clientes (lower(nome));

create table if not exists public.transportadoras (
  id bigint generated by default as identity primary key,
  nome text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists transportadoras_nome_unico
  on public.transportadoras (lower(nome));

create table if not exists public.motoristas (
  id bigint generated by default as identity primary key,
  nome text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists motoristas_nome_unico
  on public.motoristas (lower(nome));

create table if not exists public.notas (
  id bigint generated by default as identity primary key,
  cliente text not null,
  transportadora text not null,
  nf text not null,
  pedido text not null,
  volumes integer not null check (volumes > 0),
  valor numeric(12, 2) not null check (valor >= 0),
  endereco text,
  caixa jsonb not null default '[]'::jsonb,
  expedido boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.notas
  add column if not exists endereco text;

create unique index if not exists notas_nf_unica
  on public.notas (nf);

create unique index if not exists notas_pedido_unico
  on public.notas (pedido);

create or replace function public.atualizar_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists notas_atualizar_updated_at on public.notas;

create trigger notas_atualizar_updated_at
before update on public.notas
for each row
execute function public.atualizar_updated_at();

alter table public.clientes enable row level security;
alter table public.transportadoras enable row level security;
alter table public.motoristas enable row level security;
alter table public.notas enable row level security;

grant usage on schema public to anon;
grant select, insert, update, delete on public.clientes to anon;
grant select, insert, update, delete on public.transportadoras to anon;
grant select, insert, update, delete on public.motoristas to anon;
grant select, insert, update, delete on public.notas to anon;
grant usage, select on all sequences in schema public to anon;

drop policy if exists "Acesso anonimo a clientes" on public.clientes;
drop policy if exists "Acesso anonimo a transportadoras" on public.transportadoras;
drop policy if exists "Acesso anonimo a motoristas" on public.motoristas;
drop policy if exists "Acesso anonimo a notas" on public.notas;

create policy "Acesso anonimo a clientes"
  on public.clientes
  for all
  to anon
  using (true)
  with check (true);

create policy "Acesso anonimo a transportadoras"
  on public.transportadoras
  for all
  to anon
  using (true)
  with check (true);

create policy "Acesso anonimo a motoristas"
  on public.motoristas
  for all
  to anon
  using (true)
  with check (true);

create policy "Acesso anonimo a notas"
  on public.notas
  for all
  to anon
  using (true)
  with check (true);
